version: '2'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      EC2_TRACKING_SERVER_HOST: ${{ secrets.EC2_TRACKING_SERVER_HOST }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
      PG_DATABASE: ${{ secrets.PG_DATABASE }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    mem_limit: 500m
    network_mode: "host"
    # volumes:
    #   - /Users/leo/MLOPs/mlruns:/app/mlruns

  # postgresql-db:
  #   build: 
  #     context: ./postgresql
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: *******
  #     POSTGRES_USER: *****
  #     PG_HOST: postgresql-db
  #     PG_PORT: 5432
  #     POSTGRES_PASSWORD: ********