version: '2'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    mem_limit: 500m
    network_mode: "host"
    # volumes:
    #   - /Users/leo/MLOPs/mlruns:/app/mlruns

  # postgresql-db:
  #   build: 
  #     context: ./postgresql
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: *******
  #     POSTGRES_USER: *****
  #     PG_HOST: postgresql-db
  #     PG_PORT: 5432
  #     POSTGRES_PASSWORD: ********